# Generated by Django 5.0.3 on 2024-03-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=10, max_digits=100)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=100)),
                ('description', models.CharField(max_length=1000)),
                ('species', models.CharField(default='', max_length=1000)),
                ('title', models.CharField(default='', max_length=1000)),
                ('images', models.JSONField(default=list)),
                ('uid', models.IntegerField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('uPhoto', models.CharField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
