# Generated by Django 5.0.3 on 2024-04-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_animal_lat_alter_animal_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='injured',
            field=models.BooleanField(default=False),
        ),
    ]
