# Generated by Django 5.0.3 on 2024-09-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_injured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='first_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='animal',
            name='uid',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
