# Generated by Django 5.0.3 on 2024-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='photoURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
